name: "Hello actions"
description: "Greeting"
author: "thinhluu"

inputs:
  MY_NAME:
    description: "Who to greet"
    require: true
    default: "world"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
	
