name: a workflow for my hello wolrd file
on: push

jobs:
        build:
                name: Hello world action
                runs-on: ubuntu-latest
                steps:
                        -uses: action/checkout@v1
                        -uses: ./action-a
                                with:
                                        MY_NAME: "THINH"
